# Generated by Django 4.1.3 on 2022-11-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parking_slot_number', models.IntegerField()),
                ('parking_slot_status', models.CharField(max_length=1)),
            ],
        ),
    ]
