# Generated by Django 4.1.3 on 2022-11-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_parkingslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration_of_booking', models.IntegerField()),
                ('booking_status', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblParkingSpot',
            fields=[
                ('parking_slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('parking_slot_location', models.CharField(max_length=40)),
                ('parking_slot_number', models.IntegerField()),
                ('parking_slot_status', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_parking_spot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_plate_number', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'db_table': 'tbl_vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVehicleCategory',
            fields=[
                ('vehicle_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_category_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_vehicle_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVehicleOwner',
            fields=[
                ('vehicle_owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_owner_name', models.CharField(max_length=50)),
                ('vehicle_owner_contact', models.IntegerField()),
                ('vehicle_owner_email', models.CharField(max_length=30)),
                ('owner_username', models.CharField(max_length=30)),
                ('owner_password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_vehicle_owner',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='ParkingSlot',
        ),
    ]
