# Generated by Django 2.2.27 on 2022-12-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_tblbooking_tblparkingspot_tblvehicle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblvehicleowner',
            options={'managed': True},
        ),
    ]
