# Generated by Django 2.2.27 on 2022-12-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20221205_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblvehicleowner',
            options={'managed': False},
        ),
    ]
